'use strict'

define [
  'pattern/observer'
  'pattern/subject'
], (Observer, Subject) ->

  # References to our DOM elements
  controlCheckbox = document.getElementById 'mainCheckbox'
  addBtn = document.getElementById 'addNewObserver'
  container = document.getElementById 'observersContainer'

  # Concrete Subject
  # Extend the controlling checkbox with the Subject class
  # Extend an object with an extension
  extend = (extension, obj) ->
    for key of extension
      obj[key] = extension[key]
    return

  # Concrete Observer
  addNewObserver = ->
    # Create a new checkbox to be added
    check = document.createElement('input')
    check.type = 'checkbox'
    # Extend the checkbox with the Observer class
    extend new Observer, check
    # Override with custom update behaviour

    check.update = (value) ->
      @checked = value
      return

    # Add the new observer to our list of observers
    # for our main subject
    controlCheckbox.addObserver check
    # Append the item to the container
    container.appendChild check
    return

  extend new Subject, controlCheckbox
  # Clicking the checkbox will trigger notifications to its observers

  controlCheckbox.onclick = ->
    controlCheckbox.notify controlCheckbox.checked
    return

  addBtn.onclick = addNewObserver

  # ---
  # generated by js2coffee 2.0.1

  return
